owner: edjufy
repo: system-status

sites:
  - name: edjufy Frontend
    url: https://my.edjufy.com/login
  - name: edjufy Website
    url: https://www.edjufy.com/de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: www.edjufy-status.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: edjufy System Status
  introTitle: "edjufy System Status"
  introMessage: "Auf dieser Seite finden Sie den System Status der verschiedenen edjufy Anwendungen"
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.edjufy.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
